"""Build the 0.738 encrypted RbxOpenRequest2 transport record.

The low-level Request2 exchange is sent as a padded UDMUX record, not as a
normal reliable RakNet frame.  This adapter keeps the per-session header,
AEAD key, RUPP span and token blob explicit; callers must obtain those values
from the same live join and may not silently reuse an old capture.
"""
from __future__ import annotations

import ipaddress
import struct

from rbx_protocol import build_rbx_open_request2_clear_0738
from session_crypto import encrypt_body
from session_material import SessionContext
from udmux_codec import encode as encode_udmux


REQUEST2_OUTER_HEADER_BYTES = 31
REQUEST2_MTU_0738 = 1160


def encode_inverse_ipv4(address: str) -> bytes:
    """Encode the inverse little-endian IPv4 field used by Request2."""
    raw = ipaddress.IPv4Address(address).packed
    value = (~int.from_bytes(raw, "little")) & 0xFFFFFFFF
    return struct.pack("<I", value)


def build_encrypted_request2(
    *,
    context: SessionContext,
    session_key: bytes,
    udmux_header: bytes,
    rupp_aad: bytes,
    endpoint_ip: str,
    endpoint_port: int,
    token_blob: bytes | None = None,
    mtu: int = REQUEST2_MTU_0738,
    pad_to_mtu: bool = True,
    pad_length: int | None = None,
    payload_only: bool = False,
) -> bytes:
    """Return one encrypted/padded UDMUX Request2 record.

    ``session_key`` and ``rupp_aad`` are deliberately required.  They are
    generated by the Roblox session object and cannot be reconstructed from a
    place ID alone.  Passing the key through this boundary also makes it
    possible to compare the Python output against a fresh runtime trace
    without writing credentials to a report.
    """
    if len(udmux_header) != REQUEST2_OUTER_HEADER_BYTES - 4:
        raise ValueError("udmux_header must contain 27 bytes (01 11 01/02 + tags)")
    if not 576 <= int(mtu) <= 1492:
        raise ValueError("invalid MTU")
    if len(rupp_aad) != 33:
        raise ValueError("0.738 Request2 expects a 33-byte RUPP span")
    if not 0 <= int(endpoint_port) <= 0xFFFF:
        raise ValueError("endpoint_port out of range")

    token = bytes(token_blob) if token_blob is not None else None
    if token is None:
        # SessionMaterial.token_blob_candidate() is intentionally not stored
        # on the context.  A caller that has only the transient context must
        # provide the token explicitly instead of accidentally using stale
        # account data.
        raise ValueError("token_blob must be supplied from the current join")
    if len(token) != 66:
        raise ValueError("0.738 Request2 expects a 66-byte token span")

    request2_public_key = bytes(getattr(context, "request2_public_key", None)
                                or context.early_public_key)
    if len(request2_public_key) != 32:
        raise ValueError("context is missing the 32-byte Request2 public key")
    aad, plaintext = build_rbx_open_request2_clear_0738(
        server_early_public_key=request2_public_key,
        rupp_aad_type=0x11,
        rupp_aad=rupp_aad,
        client_value=context.request2_client_value,
        client_material=context.client_material_bytes(),
        mtu=int(mtu),
        encryption_selector=1,
        endpoint_ipv4=encode_inverse_ipv4(endpoint_ip),
        endpoint_port=int(endpoint_port),
        token_blob=token,
    )
    if len(aad) != 90 or len(plaintext) != 93:
        raise ValueError("unexpected 0.738 Request2 clear sizes")
    wire_body = encrypt_body(session_key, aad, plaintext)
    # The native SessionCrypto writer keeps AAD in its scratch transcript, but
    # the transport layer emits only the encrypted body.  Established records
    # therefore promote the UDMUX subflag to 02 and carry ciphertext directly
    # after the 31-byte header.  Keep the transcript form as the default for
    # fixture compatibility; live 0.738 uses payload_only=True.
    if payload_only:
        header = bytes(udmux_header)
        if len(header) >= 3 and header[2] == 1:
            header = header[:2] + b"\x02" + header[3:]
        inner = wire_body
    else:
        header = bytes(udmux_header)
        inner = aad + wire_body
    packet = encode_udmux(inner, header=header)
    if pad_to_mtu:
        # The trace advertises a 1200-byte negotiated MTU while the outer
        # UDMUX datagram is padded to 1160 bytes.  Keep those two values
        # independent so callers can reproduce either wire choice.
        target = int(pad_length if pad_length is not None else (31 + mtu if payload_only else mtu))
        if not 576 <= target <= 1492:
            raise ValueError("invalid UDMUX padding length")
        if len(packet) > target:
            raise ValueError("encrypted Request2 exceeds the selected MTU")
        packet += b"\x00" * (target - len(packet))
    return packet
